In [746]:
import numpy as np
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [747]:
arr[2]

3

In [748]:
arr[2]=5
arr

array([1, 2, 5])

In [749]:
#2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [750]:
#checking the shape of the array
print("the shape  is 2 rows and 3 columns:",arr2.shape)

the shape  is 2 rows and 3 columns: (2, 3)


In [751]:
#accessing elements from the array
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [752]:
#array of type string
arr3=np.array(['india','china','usa','mexico'])
print(arr3)

['india' 'china' 'usa' 'mexico']


In [753]:
print(arr3[1])

china


In [754]:
arr=np.arange(1,30,3)
print(arr)

[ 1  4  7 10 13 16 19 22 25 28]


In [755]:
arr=np.linspace(0,10,30)
print(arr)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]


In [756]:
#array of random values between 0 and 1 in a given shape
arr=np.random.rand(10)
print(arr)
print('\n')
arr=np.random.rand(3,4)
print(arr)


[0.99740587 0.8803344  0.1871582  0.18230824 0.63160205 0.45269015
 0.78081756 0.96127855 0.4659841  0.08694603]


[[0.41063966 0.04220497 0.84411055 0.23869533]
 [0.66999513 0.72517175 0.17258311 0.04007392]
 [0.67744895 0.81574651 0.39582414 0.2054643 ]]


In [757]:
#creating array with given values
print(np.full((5,6),20))

[[20 20 20 20 20 20]
 [20 20 20 20 20 20]
 [20 20 20 20 20 20]
 [20 20 20 20 20 20]
 [20 20 20 20 20 20]]


In [758]:
#repeating array elements
arr=[0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [759]:
#repeat array number of times
arr=[1,2,3]
print(np.tile(arr,4))

[1 2 3 1 2 3 1 2 3 1 2 3]


In [760]:
#creating identity matrix with eye
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [761]:
#creating identity matrix with identity
identity_matrix=np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [762]:
#5X5 array between 0 and 1
arr=np.random.rand(5,5)
print(arr)

[[0.16870396 0.40909239 0.15607824 0.63924376 0.45844991]
 [0.63262804 0.40580261 0.84564188 0.93031416 0.85511417]
 [0.16281476 0.54523852 0.53224631 0.56606629 0.57469664]
 [0.62508345 0.81623854 0.35578682 0.28997816 0.72991759]
 [0.50678288 0.58105663 0.0577445  0.08065451 0.58173203]]


In [763]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [764]:
#sum along the column
print(np.sum(arr2,axis=0))

[5 7 9]


In [765]:
#sum along eow
print(np.sum(arr2,axis=1))

[ 6 15]


In [766]:
#calculating mean,median,sd and vaeience
print(np.mean(arr2))
print(np.median(arr2))
print(np.std(arr2))
print(np.var(arr2))

3.5
3.5
1.707825127659933
2.9166666666666665


In [767]:
#sort an array
arr=np.random.rand(5,5)
print(arr)

[[0.37211805 0.68180408 0.51925944 0.93210923 0.69431776]
 [0.47918159 0.27730009 0.48791166 0.69198271 0.82360399]
 [0.50772752 0.15991595 0.56987887 0.65237459 0.11939475]
 [0.67032146 0.70443844 0.96728558 0.02766069 0.48635116]
 [0.32694804 0.62845026 0.88448724 0.27483527 0.04352613]]


In [768]:
#sorting along the row
print(np.sort(arr,axis=1))


[[0.37211805 0.51925944 0.68180408 0.69431776 0.93210923]
 [0.27730009 0.47918159 0.48791166 0.69198271 0.82360399]
 [0.11939475 0.15991595 0.50772752 0.56987887 0.65237459]
 [0.02766069 0.48635116 0.67032146 0.70443844 0.96728558]
 [0.04352613 0.27483527 0.32694804 0.62845026 0.88448724]]


In [769]:
#appending the elements
arr=np.array([3,4,5,6])
arr1=np.append(arr,8)
arr1

array([3, 4, 5, 6, 8])

In [770]:
arr2=np.append(arr,[8,9,10])
print(arr2)


[ 3  4  5  6  8  9 10]


In [771]:
#deleting multple elements
arr2=np.array([4,5,6,9,10,11])
print(arr2)
print('\n')
arr5=np.delete(arr2,[1,4])
print(arr5)

[ 4  5  6  9 10 11]


[ 4  6  9 11]


In [772]:
#concatinating
arr1=np.array([[1,2,3,4],[6,7,8,9]])
arr2=np.array([[11,12,13,14],[16,17,18,19]])
cat=np.concatenate((arr1,arr2),axis=1)
print(cat)

[[ 1  2  3  4 11 12 13 14]
 [ 6  7  8  9 16 17 18 19]]
